import type { NextPage } from "next";
import Head from "next/head";
import { Dashboard } from "../components/Dashboard";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>HN Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen">
        <Dashboard />
      </main>
    </div>
  );
};

export default Home;
